### ISSUE TITLE
Cannot find GHC.SrcLoc

### ISSUE THREAD

**Issue by dmjio** [sol/hspec-expectations#19]
Running into this on a build server, unsure why though.
```bash
Preprocessing library hspec-expectations-0.7.1...

src/Test/Hspec/Expectations.hs:63:18:
    Could not find module ‘GHC.SrcLoc’
    Use -v to see a list of the files searched for.
```
```haskell
#if MIN_VERSION_base(4,8,1)
#define HAS_SOURCE_LOCATIONS
{-# LANGUAGE ImplicitParams #-}
#endif
```
It seems I'm using `base-4.8.1.0`... so that means `HAS_SOURCE_LOCATIONS` is defined.
And if defined, that means `GHC.SrcLoc` is imported.
```haskell
#ifdef HAS_SOURCE_LOCATIONS

import           GHC.SrcLoc
import           GHC.Stack

#define with_loc(NAME, TYPE) NAME :: (?loc :: CallStack) => TYPE

#else

#define with_loc(NAME, TYPE) NAME :: TYPE

#endif
```
`GHC.SrcLoc` is available in `base-4.8.0.1` so in theory this shouldn't be an error right?

**Comment by sol** [comment]
Which version of GHC do you use?

**Comment by dmjio** [comment]
Interesting says `7.10.1` I believe. I ran `ghc-pkg list | grep base` and `base-4.8.1.0` was shown on the build server. It must be because I'm using the `--allow-newer` flag... at least I assume.

**Comment by dmjio** [comment]
That was it, remove `--allow-newer`, user error :) thanks for being responsive.
